version: '3.8'

services:
  bot:
    build: .
    container_name: language-bot
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /app/src
    restart: always

  db:
    image: postgres:16
    container_name: language-bot-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
